[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
dao_voting_program = "HScCa2Qkqn5DRFDXySiwhtTMNJs87hdo8DjsBxvBfyn6"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/degencodebeast/.config/solana/id.json"

[test]
startup_wait = 10000 # Increase this value (in milliseconds)

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
